//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RageOS.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public Character()
        {
            this.communications = new HashSet<Communication>();
            this.companies = new HashSet<Company>();
            this.houses = new HashSet<House>();
            this.inventories = new HashSet<Inventory>();
            this.jobs = new HashSet<Job>();
            this.messages = new HashSet<Message>();
            this.Skills = new HashSet<Skill>();
            this.vehicles = new HashSet<Vehicle>();
        }
    
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string Name { get; set; }
        public int HealthLevel { get; set; }
        public int FoodLevel { get; set; }
        public int DrinkLevel { get; set; }
        public Nullable<int> DrunkLevel { get; set; }
        public double CashMoney { get; set; }
        public Nullable<double> BankMoney { get; set; }
        public int Level { get; set; }
        public int MinutesToNextLevel { get; set; }
        public int MinutesInThisLevel { get; set; }
        public Nullable<bool> Jailed { get; set; }
        public double JailTime { get; set; }
        public Gender Gender { get; set; }
        public string SSN { get; set; }
        public double LocationX { get; set; }
        public double LocationY { get; set; }
        public double LocationZ { get; set; }
        public Nullable<int> Skin { get; set; }
    
        public virtual Account accounts { get; set; }
        public virtual HashSet<Communication> communications { get; set; }
        public virtual HashSet<Company> companies { get; set; }
        public virtual HashSet<House> houses { get; set; }
        public virtual HashSet<Inventory> inventories { get; set; }
        public virtual HashSet<Job> jobs { get; set; }
        public virtual HashSet<Message> messages { get; set; }
        public virtual HashSet<Skill> skills { get; set; }
        public virtual HashSet<Vehicle> vehicles { get; set; }
    }
}
