//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RageOS.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public Nullable<bool> HasPhone { get; set; }
        public Nullable<bool> HasShortRadio { get; set; }
        public Nullable<bool> HasLongRadio { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<double> ShortRadioFrq { get; set; }
        public Nullable<double> LongRadioFreq { get; set; }
        public Nullable<double> ShortRadioVolume { get; set; }
        public Nullable<double> LongRadioVolume { get; set; }
        public int ShortRadioSide { get; set; }
        public int LongRadioSide { get; set; }
    
        public virtual Character characters { get; set; }
    }
}
