//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RageOS.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public void Companies()
        {
            this.jobs = new HashSet<Job>();
        }
    
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public string Name { get; set; }
        public int IdentNumber { get; set; }
        public double BankMoney { get; set; }
        public CompanyType Type { get; set; }
        public double LocationX { get; set; }
        public double LocationY { get; set; }
        public double LocationZ { get; set; }
        public string CustomDataJSON { get; set; }

        public virtual Character characters { get; set; }
        public virtual HashSet<Job> jobs { get; set; }
    }
}
