//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RageOS.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public House()
        {
            this.Price = 0D;
            this.RentalObjects = 0;
            this.RentPerObject = 0D;
        }
    
        public int Id { get; set; }
        public Nullable<int> CharacterId { get; set; }
        public double LocationX { get; set; }
        public double LocationY { get; set; }
        public double LocationZ { get; set; }
        public double Price { get; set; }
        public int RentalObjects { get; set; }
        public double RentPerObject { get; set; }
        public string ObjectInterior { get; set; }
    
        public virtual Character characters { get; set; }
    }
}
