//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RageOS.Database.Models
{
    using System;
    
    public enum InventoryType : int
    {
        Personal = 0,
        Vehicle = 1,
        Weapons = 2,
        House = 3,
        Company = 4,
        Locker = 5,
        Pickupbox = 6
    }
}
