//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RageOS.Database.Models
{
    using System;
    
    public enum SkillTypes : int
    {
        Autofahren = 0,
        Farmen1 = 1,
        Farmen2 = 2,
        Farmen3 = 3,
        Schlossknacken = 20,
        Metallverarbeitung = 30
    }
}
