//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RageOS.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Id { get; set; }
        public int Owner { get; set; }
        public string Model { get; set; }
        public Nullable<bool> IsLeased { get; set; }
        public Nullable<bool> IsFinanced { get; set; }
        public Nullable<double> LeaseRate { get; set; }
        public Nullable<double> FinanceRate { get; set; }
        public Nullable<double> FinanceAmount { get; set; }
        public Nullable<double> FinanceToPay { get; set; }
    
        public virtual Character characters { get; set; }
    }
}
