//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RageOS.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicleinfo
    {
        public int Hash { get; set; }
        public string Name { get; set; }
        public string Manufactor { get; set; }
        public int Enginetype { get; set; }
        public double MinPrice { get; set; }
        public double Price { get; set; }
        public double MaxPrice { get; set; }
        public int Class { get; set; }
        public bool Blacklist { get; set; }
    }
}
